main:
	g++ -std=c++11 main.cpp vtkhdf5.cpp -o main -isystem /usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5_cpp -lhdf5
compile1:
	g++ -std=c++11 demo_vtkhdf.cpp -o demo -isystem /usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5_cpp -lhdf5